version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  app:
    build: ./
    env_file:
      - .env
    ports:
      - 8080:8080